package gostage

import (
	"errors"
	"time"
)

// HandlerID is an opaque identifier returned by [Engine.OnMessage] when
// registering an IPC message handler. Pass it to [Engine.OffMessage] to
// deregister the handler. Values are unique within an engine instance and
// are never reused.
type HandlerID int64

// Params is a type alias for map[string]any used throughout the API for
// passing initial store data to [Engine.RunSync] and [Engine.Run], providing
// resume input to [Engine.Resume], and carrying suspend metadata in [Suspend].
// Because it is an alias (not a distinct type), a plain map[string]any is
// accepted anywhere Params is expected.
//
//	engine.RunSync(ctx, wf, gostage.Params{"order_id": "ORD-123"})
type Params = map[string]any

// RunID uniquely identifies a single workflow execution run. It is a UUID v4
// string generated by the engine when [Engine.RunSync], [Engine.Run], or
// [Engine.Resume] is called. RunID values are safe to use as map keys and
// are persisted alongside the run state.
type RunID string

// Status represents the lifecycle state of a workflow run. A run transitions
// through these states during execution and settles into a terminal state
// (Completed, Failed, Bailed, or Cancelled) when finished. Suspended and
// Sleeping are non-terminal states that can transition back to Running.
type Status string

const (
	// Pending indicates the run is queued but has not begun executing.
	Pending Status = "pending"
	// Running indicates the run is actively executing steps.
	Running Status = "running"
	// Completed indicates all steps finished without error.
	Completed Status = "completed"
	// Failed indicates a step returned an error after exhausting all retries.
	Failed Status = "failed"
	// Suspended indicates the run is paused and waiting for external input
	// via [Engine.Resume].
	Suspended Status = "suspended"
	// Sleeping indicates the run is waiting for a timed delay to expire.
	// With persistence, the run is saved and no goroutine blocks; the engine's
	// timer scheduler wakes it automatically.
	Sleeping Status = "sleeping"
	// Bailed indicates the run exited early via [Bail]. This is an intentional
	// termination, not an error. The reason is available in [Result].BailReason.
	Bailed Status = "bailed"
	// Cancelled indicates the run was terminated by [Engine.Cancel] or by
	// context cancellation/deadline expiry.
	Cancelled Status = "cancelled"
)

// Result holds the outcome of a workflow run, returned by [Engine.RunSync]
// and [Engine.Wait]. Use [ResultGet] to extract typed values from the Store
// with automatic JSON round-trip type recovery.
type Result struct {
	// RunID is the unique identifier for this execution.
	RunID RunID
	// Status is the terminal status of the run. See [Status] for possible values.
	Status Status
	// Error holds the underlying error when Status is [Failed] or [Cancelled].
	// It is nil for all other statuses.
	Error error
	// BailReason holds the reason string passed to [Bail] when Status is [Bailed].
	// It is empty for all other statuses.
	BailReason string
	// Store contains a snapshot of the workflow's key-value store at the time
	// execution ended. Internal keys (prefixed with "__") are stripped before
	// the store is populated. The map is nil if the run had no state.
	Store map[string]any
	// SuspendData holds the data map passed to [Suspend] when Status is
	// [Suspended], or a map containing "wake_at" when Status is [Sleeping].
	// It is nil for all other statuses.
	SuspendData map[string]any
}

// BailError is a control flow signal returned by [Bail] to indicate
// intentional early exit. It implements the error interface but is not a
// failure; the engine catches it, sets the run status to [Bailed], and
// records the reason in [Result].BailReason. Callers should not wrap
// BailError in other errors, as the engine uses errors.As to detect it.
type BailError struct {
	Reason string
}

// Error returns the bail reason prefixed with "bail: ".
func (e *BailError) Error() string {
	return "bail: " + e.Reason
}

// SuspendError is a control flow signal returned by [Suspend] to pause the
// workflow for external input. It implements the error interface but is not a
// failure; the engine catches it, persists the workflow state, sets the run
// status to [Suspended], and stores the data in [Result].SuspendData. Callers
// should not wrap SuspendError in other errors, as the engine uses errors.As
// to detect it.
type SuspendError struct {
	Data map[string]any
}

// Error returns the string "suspended".
func (e *SuspendError) Error() string {
	return "suspended"
}

// sleepError is a control flow signal returned internally by persistent sleep
// steps. The engine catches it, sets the run status to [Sleeping], schedules
// a timer wakeup, and pins the workflow in the cache so it can be resumed
// when the timer fires. This type is not exported and cannot be returned by
// user task functions.
type sleepError struct {
	wakeAt time.Time
}

// Error returns a message with the scheduled wake time in RFC3339 format.
func (e *sleepError) Error() string {
	return "sleeping until " + e.wakeAt.Format(time.RFC3339)
}

// ResultGet extracts a typed value from a [Result]'s Store map with automatic
// type coercion. It applies the same JSON round-trip recovery as [Get]:
// numeric types are converted (e.g. float64 to int), and composite types
// (structs, slices, maps) are recovered via JSON re-marshal. Returns (zero, false)
// if r is nil, r.Store is nil, the key is missing, or the value cannot be
// coerced to T.
//
//	total, ok := gostage.ResultGet[int](result, "order_total")
func ResultGet[T any](r *Result, key string) (T, bool) {
	var zero T
	if r == nil || r.Store == nil {
		return zero, false
	}
	val, ok := r.Store[key]
	if !ok {
		return zero, false
	}
	return coerce[T](val)
}

// Sentinel errors for programmatic error checking via errors.Is.
var (
	// ErrEngineClosed is returned when an operation is attempted on an engine
	// that has been shut down via [Engine.Close].
	ErrEngineClosed = errors.New("engine is closed")

	// ErrRunNotFound is returned when a run ID does not exist in persistence.
	// The persistence layer returns a [RunNotFoundError] that matches this
	// sentinel via errors.Is.
	ErrRunNotFound = errors.New("run not found")

	// ErrRunNotSuspended is returned by [Engine.Resume] when the target run
	// is not in [Suspended] status.
	ErrRunNotSuspended = errors.New("run is not in suspended status")

	// ErrRunAlreadyActive is returned by [Engine.Resume] when a concurrent
	// resume is attempted on a run that is already executing.
	ErrRunAlreadyActive = errors.New("run is already active")

	// ErrNilWorkflow is returned by [Engine.RunSync] and [Engine.Run] when
	// a nil workflow is passed.
	ErrNilWorkflow = errors.New("workflow is nil")

	// ErrEmptyName is used in panics when [NewWorkflow] is called with an
	// empty ID string.
	ErrEmptyName = errors.New("name must not be empty")

	// ErrStateLimitExceeded is returned by [Set] when the engine's per-run
	// state entry limit (configured via [WithStateLimit]) is reached and the
	// key being set does not already exist.
	ErrStateLimitExceeded = errors.New("state entry limit exceeded")

	// ErrWorkflowNotResumable is returned when a suspended or sleeping
	// workflow cannot be resumed because its definition was not serializable.
	// This happens when the workflow uses anonymous closures for Map, DoUntil,
	// DoWhile, or Branch conditions instead of their Named variants
	// ([MapNamed], [WorkflowBuilder.DoUntilNamed], [WorkflowBuilder.DoWhileNamed], [WhenNamed]).
	ErrWorkflowNotResumable = errors.New("workflow definition was not persisted (workflows using anonymous closures cannot be resumed; use Named variants)")
)
