// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.ackWorkflowStmt, err = db.PrepareContext(ctx, ackWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query AckWorkflow: %w", err)
	}
	if q.cancelWorkflowStmt, err = db.PrepareContext(ctx, cancelWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query CancelWorkflow: %w", err)
	}
	if q.enqueueWorkflowStmt, err = db.PrepareContext(ctx, enqueueWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query EnqueueWorkflow: %w", err)
	}
	if q.getExecutionSummaryStmt, err = db.PrepareContext(ctx, getExecutionSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetExecutionSummary: %w", err)
	}
	if q.getWorkflowSummaryStmt, err = db.PrepareContext(ctx, getWorkflowSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorkflowSummary: %w", err)
	}
	if q.insertActionRunStmt, err = db.PrepareContext(ctx, insertActionRun); err != nil {
		return nil, fmt.Errorf("error preparing query InsertActionRun: %w", err)
	}
	if q.insertQueueAuditStmt, err = db.PrepareContext(ctx, insertQueueAudit); err != nil {
		return nil, fmt.Errorf("error preparing query InsertQueueAudit: %w", err)
	}
	if q.insertQueueTagsStmt, err = db.PrepareContext(ctx, insertQueueTags); err != nil {
		return nil, fmt.Errorf("error preparing query InsertQueueTags: %w", err)
	}
	if q.insertStageRunStmt, err = db.PrepareContext(ctx, insertStageRun); err != nil {
		return nil, fmt.Errorf("error preparing query InsertStageRun: %w", err)
	}
	if q.insertTelemetryEventStmt, err = db.PrepareContext(ctx, insertTelemetryEvent); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTelemetryEvent: %w", err)
	}
	if q.listActionsByWorkflowStmt, err = db.PrepareContext(ctx, listActionsByWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query ListActionsByWorkflow: %w", err)
	}
	if q.listLatestActionProgressStmt, err = db.PrepareContext(ctx, listLatestActionProgress); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestActionProgress: %w", err)
	}
	if q.listQueueAuditStmt, err = db.PrepareContext(ctx, listQueueAudit); err != nil {
		return nil, fmt.Errorf("error preparing query ListQueueAudit: %w", err)
	}
	if q.listTelemetryByWorkflowStmt, err = db.PrepareContext(ctx, listTelemetryByWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query ListTelemetryByWorkflow: %w", err)
	}
	if q.listWorkflowsFilteredStmt, err = db.PrepareContext(ctx, listWorkflowsFiltered); err != nil {
		return nil, fmt.Errorf("error preparing query ListWorkflowsFiltered: %w", err)
	}
	if q.queueStatsStmt, err = db.PrepareContext(ctx, queueStats); err != nil {
		return nil, fmt.Errorf("error preparing query QueueStats: %w", err)
	}
	if q.releaseWorkflowStmt, err = db.PrepareContext(ctx, releaseWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query ReleaseWorkflow: %w", err)
	}
	if q.updateActionStatusStmt, err = db.PrepareContext(ctx, updateActionStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateActionStatus: %w", err)
	}
	if q.updateStageStatusStmt, err = db.PrepareContext(ctx, updateStageStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStageStatus: %w", err)
	}
	if q.updateWorkflowStatusStmt, err = db.PrepareContext(ctx, updateWorkflowStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWorkflowStatus: %w", err)
	}
	if q.upsertExecutionSummaryStmt, err = db.PrepareContext(ctx, upsertExecutionSummary); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertExecutionSummary: %w", err)
	}
	if q.upsertWorkflowRunStmt, err = db.PrepareContext(ctx, upsertWorkflowRun); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertWorkflowRun: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.ackWorkflowStmt != nil {
		if cerr := q.ackWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing ackWorkflowStmt: %w", cerr)
		}
	}
	if q.cancelWorkflowStmt != nil {
		if cerr := q.cancelWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelWorkflowStmt: %w", cerr)
		}
	}
	if q.enqueueWorkflowStmt != nil {
		if cerr := q.enqueueWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing enqueueWorkflowStmt: %w", cerr)
		}
	}
	if q.getExecutionSummaryStmt != nil {
		if cerr := q.getExecutionSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getExecutionSummaryStmt: %w", cerr)
		}
	}
	if q.getWorkflowSummaryStmt != nil {
		if cerr := q.getWorkflowSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorkflowSummaryStmt: %w", cerr)
		}
	}
	if q.insertActionRunStmt != nil {
		if cerr := q.insertActionRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertActionRunStmt: %w", cerr)
		}
	}
	if q.insertQueueAuditStmt != nil {
		if cerr := q.insertQueueAuditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertQueueAuditStmt: %w", cerr)
		}
	}
	if q.insertQueueTagsStmt != nil {
		if cerr := q.insertQueueTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertQueueTagsStmt: %w", cerr)
		}
	}
	if q.insertStageRunStmt != nil {
		if cerr := q.insertStageRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertStageRunStmt: %w", cerr)
		}
	}
	if q.insertTelemetryEventStmt != nil {
		if cerr := q.insertTelemetryEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTelemetryEventStmt: %w", cerr)
		}
	}
	if q.listActionsByWorkflowStmt != nil {
		if cerr := q.listActionsByWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActionsByWorkflowStmt: %w", cerr)
		}
	}
	if q.listLatestActionProgressStmt != nil {
		if cerr := q.listLatestActionProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestActionProgressStmt: %w", cerr)
		}
	}
	if q.listQueueAuditStmt != nil {
		if cerr := q.listQueueAuditStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listQueueAuditStmt: %w", cerr)
		}
	}
	if q.listTelemetryByWorkflowStmt != nil {
		if cerr := q.listTelemetryByWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTelemetryByWorkflowStmt: %w", cerr)
		}
	}
	if q.listWorkflowsFilteredStmt != nil {
		if cerr := q.listWorkflowsFilteredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWorkflowsFilteredStmt: %w", cerr)
		}
	}
	if q.queueStatsStmt != nil {
		if cerr := q.queueStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing queueStatsStmt: %w", cerr)
		}
	}
	if q.releaseWorkflowStmt != nil {
		if cerr := q.releaseWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing releaseWorkflowStmt: %w", cerr)
		}
	}
	if q.updateActionStatusStmt != nil {
		if cerr := q.updateActionStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateActionStatusStmt: %w", cerr)
		}
	}
	if q.updateStageStatusStmt != nil {
		if cerr := q.updateStageStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStageStatusStmt: %w", cerr)
		}
	}
	if q.updateWorkflowStatusStmt != nil {
		if cerr := q.updateWorkflowStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWorkflowStatusStmt: %w", cerr)
		}
	}
	if q.upsertExecutionSummaryStmt != nil {
		if cerr := q.upsertExecutionSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertExecutionSummaryStmt: %w", cerr)
		}
	}
	if q.upsertWorkflowRunStmt != nil {
		if cerr := q.upsertWorkflowRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertWorkflowRunStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	ackWorkflowStmt              *sql.Stmt
	cancelWorkflowStmt           *sql.Stmt
	enqueueWorkflowStmt          *sql.Stmt
	getExecutionSummaryStmt      *sql.Stmt
	getWorkflowSummaryStmt       *sql.Stmt
	insertActionRunStmt          *sql.Stmt
	insertQueueAuditStmt         *sql.Stmt
	insertQueueTagsStmt          *sql.Stmt
	insertStageRunStmt           *sql.Stmt
	insertTelemetryEventStmt     *sql.Stmt
	listActionsByWorkflowStmt    *sql.Stmt
	listLatestActionProgressStmt *sql.Stmt
	listQueueAuditStmt           *sql.Stmt
	listTelemetryByWorkflowStmt  *sql.Stmt
	listWorkflowsFilteredStmt    *sql.Stmt
	queueStatsStmt               *sql.Stmt
	releaseWorkflowStmt          *sql.Stmt
	updateActionStatusStmt       *sql.Stmt
	updateStageStatusStmt        *sql.Stmt
	updateWorkflowStatusStmt     *sql.Stmt
	upsertExecutionSummaryStmt   *sql.Stmt
	upsertWorkflowRunStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		ackWorkflowStmt:              q.ackWorkflowStmt,
		cancelWorkflowStmt:           q.cancelWorkflowStmt,
		enqueueWorkflowStmt:          q.enqueueWorkflowStmt,
		getExecutionSummaryStmt:      q.getExecutionSummaryStmt,
		getWorkflowSummaryStmt:       q.getWorkflowSummaryStmt,
		insertActionRunStmt:          q.insertActionRunStmt,
		insertQueueAuditStmt:         q.insertQueueAuditStmt,
		insertQueueTagsStmt:          q.insertQueueTagsStmt,
		insertStageRunStmt:           q.insertStageRunStmt,
		insertTelemetryEventStmt:     q.insertTelemetryEventStmt,
		listActionsByWorkflowStmt:    q.listActionsByWorkflowStmt,
		listLatestActionProgressStmt: q.listLatestActionProgressStmt,
		listQueueAuditStmt:           q.listQueueAuditStmt,
		listTelemetryByWorkflowStmt:  q.listTelemetryByWorkflowStmt,
		listWorkflowsFilteredStmt:    q.listWorkflowsFilteredStmt,
		queueStatsStmt:               q.queueStatsStmt,
		releaseWorkflowStmt:          q.releaseWorkflowStmt,
		updateActionStatusStmt:       q.updateActionStatusStmt,
		updateStageStatusStmt:        q.updateStageStatusStmt,
		updateWorkflowStatusStmt:     q.updateWorkflowStatusStmt,
		upsertExecutionSummaryStmt:   q.upsertExecutionSummaryStmt,
		upsertWorkflowRunStmt:        q.upsertWorkflowRunStmt,
	}
}
