// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type ActionRun struct {
	WorkflowID  string         `json:"workflow_id"`
	StageID     string         `json:"stage_id"`
	ActionID    string         `json:"action_id"`
	Ref         sql.NullString `json:"ref"`
	Description sql.NullString `json:"description"`
	Tags        []byte         `json:"tags"`
	Dynamic     int64          `json:"dynamic"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	State       string         `json:"state"`
}

type ExecutionSummary struct {
	WorkflowID        string         `json:"workflow_id"`
	FinalStore        []byte         `json:"final_store"`
	DisabledStages    []byte         `json:"disabled_stages"`
	DisabledActions   []byte         `json:"disabled_actions"`
	RemovedStages     []byte         `json:"removed_stages"`
	RemovedActions    []byte         `json:"removed_actions"`
	Success           int64          `json:"success"`
	Error             sql.NullString `json:"error"`
	Attempt           sql.NullInt64  `json:"attempt"`
	Duration          sql.NullInt64  `json:"duration"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
	TerminationReason string         `json:"termination_reason"`
}

type QueueAudit struct {
	ID         int64          `json:"id"`
	WorkflowID string         `json:"workflow_id"`
	Event      string         `json:"event"`
	WorkerID   sql.NullString `json:"worker_id"`
	Attempt    sql.NullInt64  `json:"attempt"`
	Metadata   []byte         `json:"metadata"`
	CreatedAt  time.Time      `json:"created_at"`
}

type QueueEntry struct {
	ID         string         `json:"id"`
	Definition []byte         `json:"definition"`
	Priority   int64          `json:"priority"`
	CreatedAt  time.Time      `json:"created_at"`
	Attempts   int64          `json:"attempts"`
	State      string         `json:"state"`
	ClaimedBy  sql.NullString `json:"claimed_by"`
	ClaimedAt  sql.NullTime   `json:"claimed_at"`
	LeaseID    sql.NullString `json:"lease_id"`
	Metadata   []byte         `json:"metadata"`
}

type QueueEntryTag struct {
	EntryID string `json:"entry_id"`
	Tag     string `json:"tag"`
}

type StageRun struct {
	WorkflowID  string         `json:"workflow_id"`
	StageID     string         `json:"stage_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        []byte         `json:"tags"`
	Dynamic     int64          `json:"dynamic"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	State       string         `json:"state"`
}

type TelemetryEvent struct {
	ID         int64          `json:"id"`
	WorkflowID sql.NullString `json:"workflow_id"`
	StageID    sql.NullString `json:"stage_id"`
	ActionID   sql.NullString `json:"action_id"`
	Kind       string         `json:"kind"`
	Attempt    sql.NullInt64  `json:"attempt"`
	OccurredAt time.Time      `json:"occurred_at"`
	Message    sql.NullString `json:"message"`
	Metadata   []byte         `json:"metadata"`
	Error      sql.NullString `json:"error"`
}

type WorkflowRun struct {
	ID                string         `json:"id"`
	Name              sql.NullString `json:"name"`
	Description       sql.NullString `json:"description"`
	Type              sql.NullString `json:"type"`
	Tags              []byte         `json:"tags"`
	Metadata          []byte         `json:"metadata"`
	CreatedAt         time.Time      `json:"created_at"`
	StartedAt         sql.NullTime   `json:"started_at"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
	Duration          sql.NullInt64  `json:"duration"`
	State             string         `json:"state"`
	Success           int64          `json:"success"`
	Error             sql.NullString `json:"error"`
	TerminationReason string         `json:"termination_reason"`
}
