// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queue.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const ackWorkflow = `-- name: AckWorkflow :exec
DELETE FROM queue_entries
WHERE id = ?
`

func (q *Queries) AckWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.ackWorkflowStmt, ackWorkflow, id)
	return err
}

const cancelWorkflow = `-- name: CancelWorkflow :exec
UPDATE queue_entries
SET state = 'cancelled'
WHERE id = ?
`

func (q *Queries) CancelWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.cancelWorkflowStmt, cancelWorkflow, id)
	return err
}

const claimNextWorkflow = `-- name: ClaimNextWorkflow :one
UPDATE queue_entries
SET state = 'claimed',
    claimed_by = ?,
    claimed_at = CURRENT_TIMESTAMP,
    lease_id = ?,
    attempts = attempts + 1
WHERE id = (
    SELECT id FROM queue_entries
    WHERE state = 'pending'
    ORDER BY priority DESC, created_at ASC
    LIMIT 1
)
RETURNING id, definition, priority, created_at, attempts, claimed_by, claimed_at, lease_id, metadata
`

type ClaimNextWorkflowParams struct {
	ClaimedBy sql.NullString `json:"claimed_by"`
	LeaseID   sql.NullString `json:"lease_id"`
}

type ClaimNextWorkflowRow struct {
	ID         string         `json:"id"`
	Definition []byte         `json:"definition"`
	Priority   int64          `json:"priority"`
	CreatedAt  time.Time      `json:"created_at"`
	Attempts   int64          `json:"attempts"`
	ClaimedBy  sql.NullString `json:"claimed_by"`
	ClaimedAt  sql.NullTime   `json:"claimed_at"`
	LeaseID    sql.NullString `json:"lease_id"`
	Metadata   []byte         `json:"metadata"`
}

func (q *Queries) ClaimNextWorkflow(ctx context.Context, arg ClaimNextWorkflowParams) (ClaimNextWorkflowRow, error) {
	row := q.queryRow(ctx, q.claimNextWorkflowStmt, claimNextWorkflow, arg.ClaimedBy, arg.LeaseID)
	var i ClaimNextWorkflowRow
	err := row.Scan(
		&i.ID,
		&i.Definition,
		&i.Priority,
		&i.CreatedAt,
		&i.Attempts,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.LeaseID,
		&i.Metadata,
	)
	return i, err
}

const enqueueWorkflow = `-- name: EnqueueWorkflow :exec
INSERT INTO queue_entries (
    id, definition, priority, metadata
) VALUES (
    ?, ?, ?, ?
)
`

type EnqueueWorkflowParams struct {
	ID         string `json:"id"`
	Definition []byte `json:"definition"`
	Priority   int64  `json:"priority"`
	Metadata   []byte `json:"metadata"`
}

func (q *Queries) EnqueueWorkflow(ctx context.Context, arg EnqueueWorkflowParams) error {
	_, err := q.exec(ctx, q.enqueueWorkflowStmt, enqueueWorkflow,
		arg.ID,
		arg.Definition,
		arg.Priority,
		arg.Metadata,
	)
	return err
}

const queueStats = `-- name: QueueStats :one
SELECT
    (SELECT COUNT(*) FROM queue_entries WHERE state = 'pending') AS pending,
    (SELECT COUNT(*) FROM queue_entries WHERE state = 'claimed') AS claimed,
    (SELECT COUNT(*) FROM queue_entries WHERE state = 'cancelled') AS cancelled
`

type QueueStatsRow struct {
	Pending   int64 `json:"pending"`
	Claimed   int64 `json:"claimed"`
	Cancelled int64 `json:"cancelled"`
}

func (q *Queries) QueueStats(ctx context.Context) (QueueStatsRow, error) {
	row := q.queryRow(ctx, q.queueStatsStmt, queueStats)
	var i QueueStatsRow
	err := row.Scan(&i.Pending, &i.Claimed, &i.Cancelled)
	return i, err
}

const releaseWorkflow = `-- name: ReleaseWorkflow :exec
UPDATE queue_entries
SET state = 'pending',
    claimed_by = NULL,
    claimed_at = NULL,
    lease_id = NULL
WHERE id = ?
`

func (q *Queries) ReleaseWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.releaseWorkflowStmt, releaseWorkflow, id)
	return err
}
