// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queue.sql

package sqlc

import (
	"context"
)

const ackWorkflow = `-- name: AckWorkflow :exec
DELETE FROM queue_entries
WHERE id = ?
`

func (q *Queries) AckWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.ackWorkflowStmt, ackWorkflow, id)
	return err
}

const cancelWorkflow = `-- name: CancelWorkflow :exec
UPDATE queue_entries
SET state = 'cancelled'
WHERE id = ?
`

func (q *Queries) CancelWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.cancelWorkflowStmt, cancelWorkflow, id)
	return err
}

const enqueueWorkflow = `-- name: EnqueueWorkflow :exec
INSERT INTO queue_entries (
    id, definition, priority, metadata
) VALUES (
    ?, ?, ?, ?
)
`

type EnqueueWorkflowParams struct {
	ID         string `json:"id"`
	Definition []byte `json:"definition"`
	Priority   int64  `json:"priority"`
	Metadata   []byte `json:"metadata"`
}

func (q *Queries) EnqueueWorkflow(ctx context.Context, arg EnqueueWorkflowParams) error {
	_, err := q.exec(ctx, q.enqueueWorkflowStmt, enqueueWorkflow,
		arg.ID,
		arg.Definition,
		arg.Priority,
		arg.Metadata,
	)
	return err
}

const insertQueueTags = `-- name: InsertQueueTags :exec
INSERT INTO queue_entry_tags (entry_id, tag)
VALUES (?1, ?2)
`

type InsertQueueTagsParams struct {
	EntryID string `json:"entry_id"`
	Tag     string `json:"tag"`
}

func (q *Queries) InsertQueueTags(ctx context.Context, arg InsertQueueTagsParams) error {
	_, err := q.exec(ctx, q.insertQueueTagsStmt, insertQueueTags, arg.EntryID, arg.Tag)
	return err
}

const queueStats = `-- name: QueueStats :one
SELECT
    (SELECT COUNT(*) FROM queue_entries WHERE state = 'pending') AS pending,
    (SELECT COUNT(*) FROM queue_entries WHERE state = 'claimed') AS claimed,
    (SELECT COUNT(*) FROM queue_entries WHERE state = 'cancelled') AS cancelled
`

type QueueStatsRow struct {
	Pending   int64 `json:"pending"`
	Claimed   int64 `json:"claimed"`
	Cancelled int64 `json:"cancelled"`
}

func (q *Queries) QueueStats(ctx context.Context) (QueueStatsRow, error) {
	row := q.queryRow(ctx, q.queueStatsStmt, queueStats)
	var i QueueStatsRow
	err := row.Scan(&i.Pending, &i.Claimed, &i.Cancelled)
	return i, err
}

const releaseWorkflow = `-- name: ReleaseWorkflow :exec
UPDATE queue_entries
SET state = 'pending',
    claimed_by = NULL,
    claimed_at = NULL,
    lease_id = NULL
WHERE id = ?
`

func (q *Queries) ReleaseWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.releaseWorkflowStmt, releaseWorkflow, id)
	return err
}
