// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queue.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const ackWorkflow = `-- name: AckWorkflow :exec
DELETE FROM queue_entries
WHERE id = ?
`

func (q *Queries) AckWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.ackWorkflowStmt, ackWorkflow, id)
	return err
}

const cancelWorkflow = `-- name: CancelWorkflow :exec
UPDATE queue_entries
SET state = 'cancelled'
WHERE id = ?
`

func (q *Queries) CancelWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.cancelWorkflowStmt, cancelWorkflow, id)
	return err
}

const enqueueWorkflow = `-- name: EnqueueWorkflow :exec
INSERT INTO queue_entries (
    id, definition, priority, metadata
) VALUES (
    ?, ?, ?, ?
)
`

type EnqueueWorkflowParams struct {
	ID         string `json:"id"`
	Definition []byte `json:"definition"`
	Priority   int64  `json:"priority"`
	Metadata   []byte `json:"metadata"`
}

func (q *Queries) EnqueueWorkflow(ctx context.Context, arg EnqueueWorkflowParams) error {
	_, err := q.exec(ctx, q.enqueueWorkflowStmt, enqueueWorkflow,
		arg.ID,
		arg.Definition,
		arg.Priority,
		arg.Metadata,
	)
	return err
}

const insertQueueAudit = `-- name: InsertQueueAudit :exec
INSERT INTO queue_audit (
    workflow_id, event, worker_id, attempt, metadata
) VALUES (
    ?, ?, ?, ?, ?
)
`

type InsertQueueAuditParams struct {
	WorkflowID string         `json:"workflow_id"`
	Event      string         `json:"event"`
	WorkerID   sql.NullString `json:"worker_id"`
	Attempt    sql.NullInt64  `json:"attempt"`
	Metadata   []byte         `json:"metadata"`
}

func (q *Queries) InsertQueueAudit(ctx context.Context, arg InsertQueueAuditParams) error {
	_, err := q.exec(ctx, q.insertQueueAuditStmt, insertQueueAudit,
		arg.WorkflowID,
		arg.Event,
		arg.WorkerID,
		arg.Attempt,
		arg.Metadata,
	)
	return err
}

const insertQueueTags = `-- name: InsertQueueTags :exec
INSERT INTO queue_entry_tags (entry_id, tag)
VALUES (?1, ?2)
`

type InsertQueueTagsParams struct {
	EntryID string `json:"entry_id"`
	Tag     string `json:"tag"`
}

func (q *Queries) InsertQueueTags(ctx context.Context, arg InsertQueueTagsParams) error {
	_, err := q.exec(ctx, q.insertQueueTagsStmt, insertQueueTags, arg.EntryID, arg.Tag)
	return err
}

const listQueueAudit = `-- name: ListQueueAudit :many
SELECT
    workflow_id,
    event,
    worker_id,
    attempt,
    metadata,
    created_at
FROM queue_audit
ORDER BY id DESC
LIMIT ?
`

type ListQueueAuditRow struct {
	WorkflowID string         `json:"workflow_id"`
	Event      string         `json:"event"`
	WorkerID   sql.NullString `json:"worker_id"`
	Attempt    sql.NullInt64  `json:"attempt"`
	Metadata   []byte         `json:"metadata"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (q *Queries) ListQueueAudit(ctx context.Context, limit int64) ([]ListQueueAuditRow, error) {
	rows, err := q.query(ctx, q.listQueueAuditStmt, listQueueAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueueAuditRow
	for rows.Next() {
		var i ListQueueAuditRow
		if err := rows.Scan(
			&i.WorkflowID,
			&i.Event,
			&i.WorkerID,
			&i.Attempt,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkflowClaimed = `-- name: MarkWorkflowClaimed :one
UPDATE queue_entries
SET state = 'claimed',
    claimed_by = ?2,
    claimed_at = CURRENT_TIMESTAMP,
    lease_id = ?3,
    attempts = attempts + 1
WHERE id = ?1
  AND state = 'pending'
RETURNING attempts
`

type MarkWorkflowClaimedParams struct {
	ID        string         `json:"id"`
	ClaimedBy sql.NullString `json:"claimed_by"`
	LeaseID   sql.NullString `json:"lease_id"`
}

func (q *Queries) MarkWorkflowClaimed(ctx context.Context, arg MarkWorkflowClaimedParams) (int64, error) {
	row := q.queryRow(ctx, q.markWorkflowClaimedStmt, markWorkflowClaimed, arg.ID, arg.ClaimedBy, arg.LeaseID)
	var attempts int64
	err := row.Scan(&attempts)
	return attempts, err
}

const queueStats = `-- name: QueueStats :one
SELECT
    (SELECT COUNT(*) FROM queue_entries WHERE state = 'pending') AS pending,
    (SELECT COUNT(*) FROM queue_entries WHERE state = 'claimed') AS claimed,
    (SELECT COUNT(*) FROM queue_entries WHERE state = 'cancelled') AS cancelled
`

type QueueStatsRow struct {
	Pending   int64 `json:"pending"`
	Claimed   int64 `json:"claimed"`
	Cancelled int64 `json:"cancelled"`
}

func (q *Queries) QueueStats(ctx context.Context) (QueueStatsRow, error) {
	row := q.queryRow(ctx, q.queueStatsStmt, queueStats)
	var i QueueStatsRow
	err := row.Scan(&i.Pending, &i.Claimed, &i.Cancelled)
	return i, err
}

const releaseWorkflow = `-- name: ReleaseWorkflow :exec
UPDATE queue_entries
SET state = 'pending',
    claimed_by = NULL,
    claimed_at = NULL,
    lease_id = NULL
WHERE id = ?
`

func (q *Queries) ReleaseWorkflow(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.releaseWorkflowStmt, releaseWorkflow, id)
	return err
}

const selectAllPendingTags = `-- name: SelectAllPendingTags :many
SELECT
    qe.id,
    t.tag
FROM queue_entries qe
LEFT JOIN queue_entry_tags t ON t.entry_id = qe.id
WHERE qe.state = 'pending'
ORDER BY qe.priority DESC, qe.created_at ASC, t.tag ASC
`

type SelectAllPendingTagsRow struct {
	ID  string         `json:"id"`
	Tag sql.NullString `json:"tag"`
}

func (q *Queries) SelectAllPendingTags(ctx context.Context) ([]SelectAllPendingTagsRow, error) {
	rows, err := q.query(ctx, q.selectAllPendingTagsStmt, selectAllPendingTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectAllPendingTagsRow
	for rows.Next() {
		var i SelectAllPendingTagsRow
		if err := rows.Scan(&i.ID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPendingCandidateTags = `-- name: SelectPendingCandidateTags :many
SELECT
    t.entry_id,
    t.tag
FROM queue_entry_tags t
JOIN (
    SELECT id
    FROM queue_entries
    WHERE state = 'pending'
    ORDER BY priority DESC, created_at ASC
    LIMIT ? OFFSET ?
) AS pending ON pending.id = t.entry_id
ORDER BY t.entry_id, t.tag
`

type SelectPendingCandidateTagsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) SelectPendingCandidateTags(ctx context.Context, arg SelectPendingCandidateTagsParams) ([]QueueEntryTag, error) {
	rows, err := q.query(ctx, q.selectPendingCandidateTagsStmt, selectPendingCandidateTags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueEntryTag
	for rows.Next() {
		var i QueueEntryTag
		if err := rows.Scan(&i.EntryID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPendingCandidates = `-- name: SelectPendingCandidates :many
SELECT
    qe.id,
    qe.definition,
    qe.priority,
    qe.created_at,
    qe.attempts,
    qe.metadata
FROM queue_entries qe
WHERE qe.state = 'pending'
ORDER BY qe.priority DESC, qe.created_at ASC
LIMIT ? OFFSET ?
`

type SelectPendingCandidatesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type SelectPendingCandidatesRow struct {
	ID         string    `json:"id"`
	Definition []byte    `json:"definition"`
	Priority   int64     `json:"priority"`
	CreatedAt  time.Time `json:"created_at"`
	Attempts   int64     `json:"attempts"`
	Metadata   []byte    `json:"metadata"`
}

func (q *Queries) SelectPendingCandidates(ctx context.Context, arg SelectPendingCandidatesParams) ([]SelectPendingCandidatesRow, error) {
	rows, err := q.query(ctx, q.selectPendingCandidatesStmt, selectPendingCandidates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectPendingCandidatesRow
	for rows.Next() {
		var i SelectPendingCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Definition,
			&i.Priority,
			&i.CreatedAt,
			&i.Attempts,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
