// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: store.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getExecutionSummary = `-- name: GetExecutionSummary :one
SELECT final_store, disabled_stages, disabled_actions, removed_stages, removed_actions
FROM execution_summaries
WHERE workflow_id = ?
`

type GetExecutionSummaryRow struct {
	FinalStore      []byte `json:"final_store"`
	DisabledStages  []byte `json:"disabled_stages"`
	DisabledActions []byte `json:"disabled_actions"`
	RemovedStages   []byte `json:"removed_stages"`
	RemovedActions  []byte `json:"removed_actions"`
}

func (q *Queries) GetExecutionSummary(ctx context.Context, workflowID string) (GetExecutionSummaryRow, error) {
	row := q.queryRow(ctx, q.getExecutionSummaryStmt, getExecutionSummary, workflowID)
	var i GetExecutionSummaryRow
	err := row.Scan(
		&i.FinalStore,
		&i.DisabledStages,
		&i.DisabledActions,
		&i.RemovedStages,
		&i.RemovedActions,
	)
	return i, err
}

const getWorkflowSummary = `-- name: GetWorkflowSummary :one
SELECT id, name, description, type, tags, metadata, created_at, started_at, completed_at, duration, state, success, error
FROM workflow_runs
WHERE id = ?
`

func (q *Queries) GetWorkflowSummary(ctx context.Context, id string) (WorkflowRun, error) {
	row := q.queryRow(ctx, q.getWorkflowSummaryStmt, getWorkflowSummary, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Duration,
		&i.State,
		&i.Success,
		&i.Error,
	)
	return i, err
}

const insertActionRun = `-- name: InsertActionRun :exec
INSERT INTO action_runs (
    workflow_id, stage_id, action_id, ref, tags, dynamic, created_by, state, started_at, completed_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(workflow_id, stage_id, action_id) DO UPDATE SET
    ref = excluded.ref,
    tags = excluded.tags,
    dynamic = excluded.dynamic,
    created_by = excluded.created_by,
    state = excluded.state,
    started_at = COALESCE(excluded.started_at, action_runs.started_at),
    completed_at = COALESCE(excluded.completed_at, action_runs.completed_at)
`

type InsertActionRunParams struct {
	WorkflowID  string         `json:"workflow_id"`
	StageID     string         `json:"stage_id"`
	ActionID    string         `json:"action_id"`
	Ref         sql.NullString `json:"ref"`
	Tags        []byte         `json:"tags"`
	Dynamic     int64          `json:"dynamic"`
	CreatedBy   sql.NullString `json:"created_by"`
	State       string         `json:"state"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) InsertActionRun(ctx context.Context, arg InsertActionRunParams) error {
	_, err := q.exec(ctx, q.insertActionRunStmt, insertActionRun,
		arg.WorkflowID,
		arg.StageID,
		arg.ActionID,
		arg.Ref,
		arg.Tags,
		arg.Dynamic,
		arg.CreatedBy,
		arg.State,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const insertStageRun = `-- name: InsertStageRun :exec
INSERT INTO stage_runs (
    workflow_id, stage_id, name, tags, dynamic, created_by, state, started_at, completed_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(workflow_id, stage_id) DO UPDATE SET
    name = excluded.name,
    tags = excluded.tags,
    dynamic = excluded.dynamic,
    created_by = excluded.created_by,
    state = excluded.state,
    started_at = COALESCE(excluded.started_at, stage_runs.started_at),
    completed_at = COALESCE(excluded.completed_at, stage_runs.completed_at)
`

type InsertStageRunParams struct {
	WorkflowID  string         `json:"workflow_id"`
	StageID     string         `json:"stage_id"`
	Name        sql.NullString `json:"name"`
	Tags        []byte         `json:"tags"`
	Dynamic     int64          `json:"dynamic"`
	CreatedBy   sql.NullString `json:"created_by"`
	State       string         `json:"state"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) InsertStageRun(ctx context.Context, arg InsertStageRunParams) error {
	_, err := q.exec(ctx, q.insertStageRunStmt, insertStageRun,
		arg.WorkflowID,
		arg.StageID,
		arg.Name,
		arg.Tags,
		arg.Dynamic,
		arg.CreatedBy,
		arg.State,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const listActionsByWorkflow = `-- name: ListActionsByWorkflow :many
SELECT action_id, stage_id, ref, tags, dynamic, created_by, state, started_at, completed_at
FROM action_runs
WHERE workflow_id = ?
ORDER BY created_at ASC
`

type ListActionsByWorkflowRow struct {
	ActionID    string         `json:"action_id"`
	StageID     string         `json:"stage_id"`
	Ref         sql.NullString `json:"ref"`
	Tags        []byte         `json:"tags"`
	Dynamic     int64          `json:"dynamic"`
	CreatedBy   sql.NullString `json:"created_by"`
	State       string         `json:"state"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) ListActionsByWorkflow(ctx context.Context, workflowID string) ([]ListActionsByWorkflowRow, error) {
	rows, err := q.query(ctx, q.listActionsByWorkflowStmt, listActionsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionsByWorkflowRow
	for rows.Next() {
		var i ListActionsByWorkflowRow
		if err := rows.Scan(
			&i.ActionID,
			&i.StageID,
			&i.Ref,
			&i.Tags,
			&i.Dynamic,
			&i.CreatedBy,
			&i.State,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorkflows = `-- name: ListAllWorkflows :many
SELECT id, name, description, type, tags, metadata, created_at, started_at, completed_at, duration, state, success, error
FROM workflow_runs
ORDER BY created_at DESC
`

func (q *Queries) ListAllWorkflows(ctx context.Context) ([]WorkflowRun, error) {
	rows, err := q.query(ctx, q.listAllWorkflowsStmt, listAllWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Duration,
			&i.State,
			&i.Success,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExecutionSummary = `-- name: UpsertExecutionSummary :exec
INSERT INTO execution_summaries (
    workflow_id, final_store, disabled_stages, disabled_actions, removed_stages, removed_actions
) VALUES (
    ?, ?, ?, ?, ?, ?
)
ON CONFLICT(workflow_id) DO UPDATE SET
    final_store = excluded.final_store,
    disabled_stages = excluded.disabled_stages,
    disabled_actions = excluded.disabled_actions,
    removed_stages = excluded.removed_stages,
    removed_actions = excluded.removed_actions
`

type UpsertExecutionSummaryParams struct {
	WorkflowID      string `json:"workflow_id"`
	FinalStore      []byte `json:"final_store"`
	DisabledStages  []byte `json:"disabled_stages"`
	DisabledActions []byte `json:"disabled_actions"`
	RemovedStages   []byte `json:"removed_stages"`
	RemovedActions  []byte `json:"removed_actions"`
}

func (q *Queries) UpsertExecutionSummary(ctx context.Context, arg UpsertExecutionSummaryParams) error {
	_, err := q.exec(ctx, q.upsertExecutionSummaryStmt, upsertExecutionSummary,
		arg.WorkflowID,
		arg.FinalStore,
		arg.DisabledStages,
		arg.DisabledActions,
		arg.RemovedStages,
		arg.RemovedActions,
	)
	return err
}

const upsertWorkflowRun = `-- name: UpsertWorkflowRun :exec
INSERT INTO workflow_runs (
    id, name, description, type, tags, metadata, created_at, state, success, error, started_at, completed_at, duration
) VALUES (
    ?, ?, ?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP), ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    type = excluded.type,
    tags = excluded.tags,
    metadata = excluded.metadata,
    state = excluded.state,
    success = excluded.success,
    error = excluded.error,
    started_at = COALESCE(excluded.started_at, workflow_runs.started_at),
    completed_at = COALESCE(excluded.completed_at, workflow_runs.completed_at),
    duration = COALESCE(excluded.duration, workflow_runs.duration)
`

type UpsertWorkflowRunParams struct {
	ID          string         `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Type        sql.NullString `json:"type"`
	Tags        []byte         `json:"tags"`
	Metadata    []byte         `json:"metadata"`
	Column7     interface{}    `json:"column_7"`
	State       string         `json:"state"`
	Success     int64          `json:"success"`
	Error       sql.NullString `json:"error"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	Duration    sql.NullInt64  `json:"duration"`
}

func (q *Queries) UpsertWorkflowRun(ctx context.Context, arg UpsertWorkflowRunParams) error {
	_, err := q.exec(ctx, q.upsertWorkflowRunStmt, upsertWorkflowRun,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Tags,
		arg.Metadata,
		arg.Column7,
		arg.State,
		arg.Success,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Duration,
	)
	return err
}
