// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: store.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getExecutionSummary = `-- name: GetExecutionSummary :one
SELECT final_store, disabled_stages, disabled_actions, removed_stages, removed_actions, success, error, attempt, duration, completed_at, termination_reason
FROM execution_summaries
WHERE workflow_id = ?
`

type GetExecutionSummaryRow struct {
	FinalStore        []byte         `json:"final_store"`
	DisabledStages    []byte         `json:"disabled_stages"`
	DisabledActions   []byte         `json:"disabled_actions"`
	RemovedStages     []byte         `json:"removed_stages"`
	RemovedActions    []byte         `json:"removed_actions"`
	Success           int64          `json:"success"`
	Error             sql.NullString `json:"error"`
	Attempt           sql.NullInt64  `json:"attempt"`
	Duration          sql.NullInt64  `json:"duration"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
	TerminationReason string         `json:"termination_reason"`
}

func (q *Queries) GetExecutionSummary(ctx context.Context, workflowID string) (GetExecutionSummaryRow, error) {
	row := q.queryRow(ctx, q.getExecutionSummaryStmt, getExecutionSummary, workflowID)
	var i GetExecutionSummaryRow
	err := row.Scan(
		&i.FinalStore,
		&i.DisabledStages,
		&i.DisabledActions,
		&i.RemovedStages,
		&i.RemovedActions,
		&i.Success,
		&i.Error,
		&i.Attempt,
		&i.Duration,
		&i.CompletedAt,
		&i.TerminationReason,
	)
	return i, err
}

const getWorkflowSummary = `-- name: GetWorkflowSummary :one
SELECT id, name, description, type, tags, metadata, created_at, started_at, completed_at, duration, state, success, error, termination_reason
FROM workflow_runs
WHERE id = ?
`

func (q *Queries) GetWorkflowSummary(ctx context.Context, id string) (WorkflowRun, error) {
	row := q.queryRow(ctx, q.getWorkflowSummaryStmt, getWorkflowSummary, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Duration,
		&i.State,
		&i.Success,
		&i.Error,
		&i.TerminationReason,
	)
	return i, err
}

const insertActionRun = `-- name: InsertActionRun :exec
INSERT INTO action_runs (
    workflow_id, stage_id, action_id, ref, description, tags, dynamic, created_by, state, started_at, completed_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(workflow_id, stage_id, action_id) DO UPDATE SET
    ref = excluded.ref,
    description = excluded.description,
    tags = excluded.tags,
    dynamic = excluded.dynamic,
    created_by = excluded.created_by,
    state = excluded.state,
    started_at = COALESCE(excluded.started_at, action_runs.started_at),
    completed_at = COALESCE(excluded.completed_at, action_runs.completed_at)
`

type InsertActionRunParams struct {
	WorkflowID  string         `json:"workflow_id"`
	StageID     string         `json:"stage_id"`
	ActionID    string         `json:"action_id"`
	Ref         sql.NullString `json:"ref"`
	Description sql.NullString `json:"description"`
	Tags        []byte         `json:"tags"`
	Dynamic     int64          `json:"dynamic"`
	CreatedBy   sql.NullString `json:"created_by"`
	State       string         `json:"state"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) InsertActionRun(ctx context.Context, arg InsertActionRunParams) error {
	_, err := q.exec(ctx, q.insertActionRunStmt, insertActionRun,
		arg.WorkflowID,
		arg.StageID,
		arg.ActionID,
		arg.Ref,
		arg.Description,
		arg.Tags,
		arg.Dynamic,
		arg.CreatedBy,
		arg.State,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const insertStageRun = `-- name: InsertStageRun :exec
INSERT INTO stage_runs (
    workflow_id, stage_id, name, description, tags, dynamic, created_by, state, started_at, completed_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(workflow_id, stage_id) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    tags = excluded.tags,
    dynamic = excluded.dynamic,
    created_by = excluded.created_by,
    state = excluded.state,
    started_at = COALESCE(excluded.started_at, stage_runs.started_at),
    completed_at = COALESCE(excluded.completed_at, stage_runs.completed_at)
`

type InsertStageRunParams struct {
	WorkflowID  string         `json:"workflow_id"`
	StageID     string         `json:"stage_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        []byte         `json:"tags"`
	Dynamic     int64          `json:"dynamic"`
	CreatedBy   sql.NullString `json:"created_by"`
	State       string         `json:"state"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) InsertStageRun(ctx context.Context, arg InsertStageRunParams) error {
	_, err := q.exec(ctx, q.insertStageRunStmt, insertStageRun,
		arg.WorkflowID,
		arg.StageID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.Dynamic,
		arg.CreatedBy,
		arg.State,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const listActionsByWorkflow = `-- name: ListActionsByWorkflow :many
SELECT action_id, stage_id, ref, description, tags, dynamic, created_by, state, started_at, completed_at
FROM action_runs
WHERE workflow_id = ?
ORDER BY created_at ASC
`

type ListActionsByWorkflowRow struct {
	ActionID    string         `json:"action_id"`
	StageID     string         `json:"stage_id"`
	Ref         sql.NullString `json:"ref"`
	Description sql.NullString `json:"description"`
	Tags        []byte         `json:"tags"`
	Dynamic     int64          `json:"dynamic"`
	CreatedBy   sql.NullString `json:"created_by"`
	State       string         `json:"state"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

func (q *Queries) ListActionsByWorkflow(ctx context.Context, workflowID string) ([]ListActionsByWorkflowRow, error) {
	rows, err := q.query(ctx, q.listActionsByWorkflowStmt, listActionsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionsByWorkflowRow
	for rows.Next() {
		var i ListActionsByWorkflowRow
		if err := rows.Scan(
			&i.ActionID,
			&i.StageID,
			&i.Ref,
			&i.Description,
			&i.Tags,
			&i.Dynamic,
			&i.CreatedBy,
			&i.State,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsFiltered = `-- name: ListWorkflowsFiltered :many
SELECT id, name, description, type, tags, metadata, created_at, started_at, completed_at, duration, state, success, error, termination_reason
FROM workflow_runs
WHERE
    (
        ?1 IS NULL
        OR EXISTS (
            SELECT 1
            FROM json_each(COALESCE(?1, '[]')) AS state_filter
            WHERE workflow_runs.state = state_filter.value
        )
    )
    AND (
        ?2 IS NULL
        OR EXISTS (
            SELECT 1
            FROM json_each(COALESCE(?2, '[]')) AS type_filter
            WHERE workflow_runs.type = type_filter.value
        )
    )
    AND (
        ?3 IS NULL
        OR EXISTS (
            SELECT 1
            FROM json_each(COALESCE(?3, '[]')) AS tag_filter
            WHERE EXISTS (
                SELECT 1
                FROM json_each(workflow_runs.tags) AS wf_tag
                WHERE wf_tag.value = tag_filter.value
            )
        )
    )
    AND (?4 IS NULL OR workflow_runs.created_at >= ?4)
    AND (?5 IS NULL OR workflow_runs.created_at <= ?5)
ORDER BY created_at DESC
LIMIT CASE WHEN ?7 IS NULL OR ?7 <= 0 THEN -1 ELSE ?7 END
OFFSET COALESCE(?6, 0)
`

type ListWorkflowsFilteredParams struct {
	StatesJson interface{} `json:"states_json"`
	TypeJson   interface{} `json:"type_json"`
	TagsJson   interface{} `json:"tags_json"`
	FromTime   interface{} `json:"from_time"`
	ToTime     interface{} `json:"to_time"`
	OffsetRows interface{} `json:"offset_rows"`
	LimitRows  interface{} `json:"limit_rows"`
}

func (q *Queries) ListWorkflowsFiltered(ctx context.Context, arg ListWorkflowsFilteredParams) ([]WorkflowRun, error) {
	rows, err := q.query(ctx, q.listWorkflowsFilteredStmt, listWorkflowsFiltered,
		arg.StatesJson,
		arg.TypeJson,
		arg.TagsJson,
		arg.FromTime,
		arg.ToTime,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Duration,
			&i.State,
			&i.Success,
			&i.Error,
			&i.TerminationReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActionStatus = `-- name: UpdateActionStatus :exec
UPDATE action_runs
SET
    state = ?1,
    started_at = COALESCE(?2, action_runs.started_at),
    completed_at = COALESCE(?3, action_runs.completed_at)
WHERE workflow_id = ?4
  AND stage_id = ?5
  AND action_id = ?6
`

type UpdateActionStatusParams struct {
	State       string       `json:"state"`
	StartedAt   sql.NullTime `json:"started_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	WorkflowID  string       `json:"workflow_id"`
	StageID     string       `json:"stage_id"`
	ActionID    string       `json:"action_id"`
}

func (q *Queries) UpdateActionStatus(ctx context.Context, arg UpdateActionStatusParams) error {
	_, err := q.exec(ctx, q.updateActionStatusStmt, updateActionStatus,
		arg.State,
		arg.StartedAt,
		arg.CompletedAt,
		arg.WorkflowID,
		arg.StageID,
		arg.ActionID,
	)
	return err
}

const updateStageStatus = `-- name: UpdateStageStatus :exec
UPDATE stage_runs
SET
    state = ?1,
    started_at = COALESCE(?2, stage_runs.started_at),
    completed_at = COALESCE(?3, stage_runs.completed_at)
WHERE workflow_id = ?4
  AND stage_id = ?5
`

type UpdateStageStatusParams struct {
	State       string       `json:"state"`
	StartedAt   sql.NullTime `json:"started_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	WorkflowID  string       `json:"workflow_id"`
	StageID     string       `json:"stage_id"`
}

func (q *Queries) UpdateStageStatus(ctx context.Context, arg UpdateStageStatusParams) error {
	_, err := q.exec(ctx, q.updateStageStatusStmt, updateStageStatus,
		arg.State,
		arg.StartedAt,
		arg.CompletedAt,
		arg.WorkflowID,
		arg.StageID,
	)
	return err
}

const updateWorkflowStatus = `-- name: UpdateWorkflowStatus :exec
UPDATE workflow_runs
SET
    state = ?1,
    started_at = COALESCE(?2, workflow_runs.started_at),
    completed_at = COALESCE(?3, workflow_runs.completed_at),
    duration = COALESCE(?4, workflow_runs.duration),
    success = COALESCE(?5, workflow_runs.success),
    error = COALESCE(?6, workflow_runs.error),
    termination_reason = COALESCE(?7, workflow_runs.termination_reason)
WHERE id = ?8
`

type UpdateWorkflowStatusParams struct {
	State             string         `json:"state"`
	StartedAt         sql.NullTime   `json:"started_at"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
	Duration          sql.NullInt64  `json:"duration"`
	Success           sql.NullInt64  `json:"success"`
	Error             sql.NullString `json:"error"`
	TerminationReason sql.NullString `json:"termination_reason"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateWorkflowStatus(ctx context.Context, arg UpdateWorkflowStatusParams) error {
	_, err := q.exec(ctx, q.updateWorkflowStatusStmt, updateWorkflowStatus,
		arg.State,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Duration,
		arg.Success,
		arg.Error,
		arg.TerminationReason,
		arg.ID,
	)
	return err
}

const upsertExecutionSummary = `-- name: UpsertExecutionSummary :exec
INSERT INTO execution_summaries (
    workflow_id,
    final_store,
    disabled_stages,
    disabled_actions,
    removed_stages,
    removed_actions,
    success,
    error,
    attempt,
    duration,
    completed_at,
    termination_reason
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(workflow_id) DO UPDATE SET
    final_store = excluded.final_store,
    disabled_stages = excluded.disabled_stages,
    disabled_actions = excluded.disabled_actions,
    removed_stages = excluded.removed_stages,
    removed_actions = excluded.removed_actions,
    success = excluded.success,
    error = excluded.error,
    attempt = excluded.attempt,
    duration = excluded.duration,
    completed_at = excluded.completed_at,
    termination_reason = excluded.termination_reason
`

type UpsertExecutionSummaryParams struct {
	WorkflowID        string         `json:"workflow_id"`
	FinalStore        []byte         `json:"final_store"`
	DisabledStages    []byte         `json:"disabled_stages"`
	DisabledActions   []byte         `json:"disabled_actions"`
	RemovedStages     []byte         `json:"removed_stages"`
	RemovedActions    []byte         `json:"removed_actions"`
	Success           int64          `json:"success"`
	Error             sql.NullString `json:"error"`
	Attempt           sql.NullInt64  `json:"attempt"`
	Duration          sql.NullInt64  `json:"duration"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
	TerminationReason string         `json:"termination_reason"`
}

func (q *Queries) UpsertExecutionSummary(ctx context.Context, arg UpsertExecutionSummaryParams) error {
	_, err := q.exec(ctx, q.upsertExecutionSummaryStmt, upsertExecutionSummary,
		arg.WorkflowID,
		arg.FinalStore,
		arg.DisabledStages,
		arg.DisabledActions,
		arg.RemovedStages,
		arg.RemovedActions,
		arg.Success,
		arg.Error,
		arg.Attempt,
		arg.Duration,
		arg.CompletedAt,
		arg.TerminationReason,
	)
	return err
}

const upsertWorkflowRun = `-- name: UpsertWorkflowRun :exec
INSERT INTO workflow_runs (
    id, name, description, type, tags, metadata, created_at, state, success, error, started_at, completed_at, duration, termination_reason
) VALUES (
    ?, ?, ?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP), ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    type = excluded.type,
    tags = excluded.tags,
    metadata = excluded.metadata,
    state = excluded.state,
    success = excluded.success,
    error = excluded.error,
    started_at = COALESCE(excluded.started_at, workflow_runs.started_at),
    completed_at = COALESCE(excluded.completed_at, workflow_runs.completed_at),
    duration = COALESCE(excluded.duration, workflow_runs.duration),
    termination_reason = excluded.termination_reason
`

type UpsertWorkflowRunParams struct {
	ID                string         `json:"id"`
	Name              sql.NullString `json:"name"`
	Description       sql.NullString `json:"description"`
	Type              sql.NullString `json:"type"`
	Tags              []byte         `json:"tags"`
	Metadata          []byte         `json:"metadata"`
	Column7           interface{}    `json:"column_7"`
	State             string         `json:"state"`
	Success           int64          `json:"success"`
	Error             sql.NullString `json:"error"`
	StartedAt         sql.NullTime   `json:"started_at"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
	Duration          sql.NullInt64  `json:"duration"`
	TerminationReason string         `json:"termination_reason"`
}

func (q *Queries) UpsertWorkflowRun(ctx context.Context, arg UpsertWorkflowRunParams) error {
	_, err := q.exec(ctx, q.upsertWorkflowRunStmt, upsertWorkflowRun,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Tags,
		arg.Metadata,
		arg.Column7,
		arg.State,
		arg.Success,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Duration,
		arg.TerminationReason,
	)
	return err
}
