// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: telemetry.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const insertTelemetryEvent = `-- name: InsertTelemetryEvent :exec
INSERT INTO telemetry_events (
    workflow_id, stage_id, action_id, kind, attempt, occurred_at, message, metadata, error
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertTelemetryEventParams struct {
	WorkflowID sql.NullString `json:"workflow_id"`
	StageID    sql.NullString `json:"stage_id"`
	ActionID   sql.NullString `json:"action_id"`
	Kind       string         `json:"kind"`
	Attempt    sql.NullInt64  `json:"attempt"`
	OccurredAt time.Time      `json:"occurred_at"`
	Message    sql.NullString `json:"message"`
	Metadata   []byte         `json:"metadata"`
	Error      sql.NullString `json:"error"`
}

func (q *Queries) InsertTelemetryEvent(ctx context.Context, arg InsertTelemetryEventParams) error {
	_, err := q.exec(ctx, q.insertTelemetryEventStmt, insertTelemetryEvent,
		arg.WorkflowID,
		arg.StageID,
		arg.ActionID,
		arg.Kind,
		arg.Attempt,
		arg.OccurredAt,
		arg.Message,
		arg.Metadata,
		arg.Error,
	)
	return err
}

const listTelemetryByWorkflow = `-- name: ListTelemetryByWorkflow :many
SELECT workflow_id, stage_id, action_id, kind, attempt, occurred_at, message, metadata, error
FROM telemetry_events
WHERE workflow_id = ?
ORDER BY occurred_at ASC
`

type ListTelemetryByWorkflowRow struct {
	WorkflowID sql.NullString `json:"workflow_id"`
	StageID    sql.NullString `json:"stage_id"`
	ActionID   sql.NullString `json:"action_id"`
	Kind       string         `json:"kind"`
	Attempt    sql.NullInt64  `json:"attempt"`
	OccurredAt time.Time      `json:"occurred_at"`
	Message    sql.NullString `json:"message"`
	Metadata   []byte         `json:"metadata"`
	Error      sql.NullString `json:"error"`
}

func (q *Queries) ListTelemetryByWorkflow(ctx context.Context, workflowID sql.NullString) ([]ListTelemetryByWorkflowRow, error) {
	rows, err := q.query(ctx, q.listTelemetryByWorkflowStmt, listTelemetryByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTelemetryByWorkflowRow
	for rows.Next() {
		var i ListTelemetryByWorkflowRow
		if err := rows.Scan(
			&i.WorkflowID,
			&i.StageID,
			&i.ActionID,
			&i.Kind,
			&i.Attempt,
			&i.OccurredAt,
			&i.Message,
			&i.Metadata,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
