// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: control.proto

package processproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminationReason int32

const (
	TerminationReason_TERMINATION_UNKNOWN       TerminationReason = 0
	TerminationReason_TERMINATION_SUCCESS       TerminationReason = 1
	TerminationReason_TERMINATION_FAILURE       TerminationReason = 2
	TerminationReason_TERMINATION_USER_CANCEL   TerminationReason = 3
	TerminationReason_TERMINATION_POLICY_CANCEL TerminationReason = 4
	TerminationReason_TERMINATION_TIMEOUT       TerminationReason = 5
)

// Enum value maps for TerminationReason.
var (
	TerminationReason_name = map[int32]string{
		0: "TERMINATION_UNKNOWN",
		1: "TERMINATION_SUCCESS",
		2: "TERMINATION_FAILURE",
		3: "TERMINATION_USER_CANCEL",
		4: "TERMINATION_POLICY_CANCEL",
		5: "TERMINATION_TIMEOUT",
	}
	TerminationReason_value = map[string]int32{
		"TERMINATION_UNKNOWN":       0,
		"TERMINATION_SUCCESS":       1,
		"TERMINATION_FAILURE":       2,
		"TERMINATION_USER_CANCEL":   3,
		"TERMINATION_POLICY_CANCEL": 4,
		"TERMINATION_TIMEOUT":       5,
	}
)

func (x TerminationReason) Enum() *TerminationReason {
	p := new(TerminationReason)
	*p = x
	return p
}

func (x TerminationReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminationReason) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (TerminationReason) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x TerminationReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminationReason.Descriptor instead.
func (TerminationReason) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

// ControlEnvelope wraps all messages exchanged over the bidirectional
// parent/child control stream. Each envelope carries a single typed payload.
type ControlEnvelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControlEnvelope_Register
	//	*ControlEnvelope_RegisterAck
	//	*ControlEnvelope_LeaseGrant
	//	*ControlEnvelope_LeaseAck
	//	*ControlEnvelope_Cancel
	//	*ControlEnvelope_Heartbeat
	//	*ControlEnvelope_Shutdown
	//	*ControlEnvelope_Telemetry
	//	*ControlEnvelope_Diagnostic
	//	*ControlEnvelope_ConfigUpdate
	Body          isControlEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEnvelope) Reset() {
	*x = ControlEnvelope{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEnvelope) ProtoMessage() {}

func (x *ControlEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEnvelope.ProtoReflect.Descriptor instead.
func (*ControlEnvelope) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *ControlEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ControlEnvelope) GetBody() isControlEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControlEnvelope) GetRegister() *RegisterNode {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ControlEnvelope) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ControlEnvelope) GetLeaseGrant() *LeaseGrant {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_LeaseGrant); ok {
			return x.LeaseGrant
		}
	}
	return nil
}

func (x *ControlEnvelope) GetLeaseAck() *LeaseAck {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_LeaseAck); ok {
			return x.LeaseAck
		}
	}
	return nil
}

func (x *ControlEnvelope) GetCancel() *CancelWorkflow {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ControlEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ControlEnvelope) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ControlEnvelope) GetTelemetry() *TelemetryForward {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *ControlEnvelope) GetDiagnostic() *DiagnosticForward {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_Diagnostic); ok {
			return x.Diagnostic
		}
	}
	return nil
}

func (x *ControlEnvelope) GetConfigUpdate() *ChildConfigUpdate {
	if x != nil {
		if x, ok := x.Body.(*ControlEnvelope_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

type isControlEnvelope_Body interface {
	isControlEnvelope_Body()
}

type ControlEnvelope_Register struct {
	Register *RegisterNode `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type ControlEnvelope_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,3,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ControlEnvelope_LeaseGrant struct {
	LeaseGrant *LeaseGrant `protobuf:"bytes,4,opt,name=lease_grant,json=leaseGrant,proto3,oneof"`
}

type ControlEnvelope_LeaseAck struct {
	LeaseAck *LeaseAck `protobuf:"bytes,5,opt,name=lease_ack,json=leaseAck,proto3,oneof"`
}

type ControlEnvelope_Cancel struct {
	Cancel *CancelWorkflow `protobuf:"bytes,6,opt,name=cancel,proto3,oneof"`
}

type ControlEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,7,opt,name=heartbeat,proto3,oneof"`
}

type ControlEnvelope_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,8,opt,name=shutdown,proto3,oneof"`
}

type ControlEnvelope_Telemetry struct {
	Telemetry *TelemetryForward `protobuf:"bytes,9,opt,name=telemetry,proto3,oneof"`
}

type ControlEnvelope_Diagnostic struct {
	Diagnostic *DiagnosticForward `protobuf:"bytes,10,opt,name=diagnostic,proto3,oneof"`
}

type ControlEnvelope_ConfigUpdate struct {
	ConfigUpdate *ChildConfigUpdate `protobuf:"bytes,11,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

func (*ControlEnvelope_Register) isControlEnvelope_Body() {}

func (*ControlEnvelope_RegisterAck) isControlEnvelope_Body() {}

func (*ControlEnvelope_LeaseGrant) isControlEnvelope_Body() {}

func (*ControlEnvelope_LeaseAck) isControlEnvelope_Body() {}

func (*ControlEnvelope_Cancel) isControlEnvelope_Body() {}

func (*ControlEnvelope_Heartbeat) isControlEnvelope_Body() {}

func (*ControlEnvelope_Shutdown) isControlEnvelope_Body() {}

func (*ControlEnvelope_Telemetry) isControlEnvelope_Body() {}

func (*ControlEnvelope_Diagnostic) isControlEnvelope_Body() {}

func (*ControlEnvelope_ConfigUpdate) isControlEnvelope_Body() {}

// RegisterNode is sent by a child process when it connects to the parent.
type RegisterNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ChildType     string                 `protobuf:"bytes,2,opt,name=child_type,json=childType,proto3" json:"child_type,omitempty"`
	Pools         []*ChildPool           `protobuf:"bytes,3,rep,name=pools,proto3" json:"pools,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Runtime       *RuntimeInfo           `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"`
	AuthToken     string                 `protobuf:"bytes,6,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNode) Reset() {
	*x = RegisterNode{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNode) ProtoMessage() {}

func (x *RegisterNode) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNode.ProtoReflect.Descriptor instead.
func (*RegisterNode) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNode) GetChildType() string {
	if x != nil {
		return x.ChildType
	}
	return ""
}

func (x *RegisterNode) GetPools() []*ChildPool {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *RegisterNode) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterNode) GetRuntime() *RuntimeInfo {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *RegisterNode) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// RegisterAck confirms registration (parent -> child) and conveys
// connection parameters such as heartbeat interval.
type RegisterAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,1,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	HeartbeatTimeout  *durationpb.Duration   `protobuf:"bytes,2,opt,name=heartbeat_timeout,json=heartbeatTimeout,proto3" json:"heartbeat_timeout,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAck) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

func (x *RegisterAck) GetHeartbeatTimeout() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatTimeout
	}
	return nil
}

// ChildPool mirrors gostage PoolConfig fields relevant to remote children.
type ChildPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slots         uint32                 `protobuf:"varint,2,opt,name=slots,proto3" json:"slots,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildPool) Reset() {
	*x = ChildPool{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildPool) ProtoMessage() {}

func (x *ChildPool) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildPool.ProtoReflect.Descriptor instead.
func (*ChildPool) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *ChildPool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChildPool) GetSlots() uint32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

func (x *ChildPool) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ChildPool) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GoVersion     string                 `protobuf:"bytes,2,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Binary        string                 `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	GitCommit     string                 `protobuf:"bytes,6,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuntimeInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *RuntimeInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RuntimeInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RuntimeInfo) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *RuntimeInfo) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

// LeaseGrant delivers a workflow to a child for execution.
type LeaseGrant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId     string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	LeaseId        string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Attempt        int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	WorkflowRef    string                 `protobuf:"bytes,4,opt,name=workflow_ref,json=workflowRef,proto3" json:"workflow_ref,omitempty"`
	DefinitionJson []byte                 `protobuf:"bytes,5,opt,name=definition_json,json=definitionJson,proto3" json:"definition_json,omitempty"`
	StoreJson      []byte                 `protobuf:"bytes,6,opt,name=store_json,json=storeJson,proto3" json:"store_json,omitempty"`
	MetadataJson   []byte                 `protobuf:"bytes,7,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Priority       int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseGrant) Reset() {
	*x = LeaseGrant{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrant) ProtoMessage() {}

func (x *LeaseGrant) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrant.ProtoReflect.Descriptor instead.
func (*LeaseGrant) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *LeaseGrant) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *LeaseGrant) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseGrant) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *LeaseGrant) GetWorkflowRef() string {
	if x != nil {
		return x.WorkflowRef
	}
	return ""
}

func (x *LeaseGrant) GetDefinitionJson() []byte {
	if x != nil {
		return x.DefinitionJson
	}
	return nil
}

func (x *LeaseGrant) GetStoreJson() []byte {
	if x != nil {
		return x.StoreJson
	}
	return nil
}

func (x *LeaseGrant) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *LeaseGrant) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// LeaseAck is sent by the child when a workflow finishes executing.
type LeaseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Summary       *ResultSummary         `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseAck) Reset() {
	*x = LeaseAck{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseAck) ProtoMessage() {}

func (x *LeaseAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseAck.ProtoReflect.Descriptor instead.
func (*LeaseAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *LeaseAck) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *LeaseAck) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseAck) GetSummary() *ResultSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// CancelWorkflow requests a running child to cancel execution.
type CancelWorkflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflow) Reset() {
	*x = CancelWorkflow{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflow) ProtoMessage() {}

func (x *CancelWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflow.ProtoReflect.Descriptor instead.
func (*CancelWorkflow) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *CancelWorkflow) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

// Heartbeat is exchanged periodically to keep the connection alive.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Shutdown indicates either side intends to close the connection gracefully.
type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// TelemetryForward transports telemetry events emitted by the child
// so the parent can fan them out to registered sinks.
type TelemetryForward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventJson     []byte                 `protobuf:"bytes,1,opt,name=event_json,json=eventJson,proto3" json:"event_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryForward) Reset() {
	*x = TelemetryForward{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryForward) ProtoMessage() {}

func (x *TelemetryForward) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryForward.ProtoReflect.Descriptor instead.
func (*TelemetryForward) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *TelemetryForward) GetEventJson() []byte {
	if x != nil {
		return x.EventJson
	}
	return nil
}

// DiagnosticForward transports diagnostics from the child into the parent's
// diagnostic stream.
type DiagnosticForward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticForward) Reset() {
	*x = DiagnosticForward{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticForward) ProtoMessage() {}

func (x *DiagnosticForward) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticForward.ProtoReflect.Descriptor instead.
func (*DiagnosticForward) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *DiagnosticForward) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *DiagnosticForward) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *DiagnosticForward) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *DiagnosticForward) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DiagnosticForward) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

// ChildConfigUpdate lets the parent push configuration changes to a child.
type ChildConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetadataJson  []byte                 `protobuf:"bytes,1,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildConfigUpdate) Reset() {
	*x = ChildConfigUpdate{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildConfigUpdate) ProtoMessage() {}

func (x *ChildConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildConfigUpdate.ProtoReflect.Descriptor instead.
func (*ChildConfigUpdate) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *ChildConfigUpdate) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

// ResultSummary mirrors state.ResultSummary in a transport friendly form.
type ResultSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Attempt         int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	OutputJson      []byte                 `protobuf:"bytes,4,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Duration        *durationpb.Duration   `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	CompletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DisabledStages  map[string]bool        `protobuf:"bytes,7,rep,name=disabled_stages,json=disabledStages,proto3" json:"disabled_stages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DisabledActions map[string]bool        `protobuf:"bytes,8,rep,name=disabled_actions,json=disabledActions,proto3" json:"disabled_actions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RemovedStages   map[string]string      `protobuf:"bytes,9,rep,name=removed_stages,json=removedStages,proto3" json:"removed_stages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedActions  map[string]string      `protobuf:"bytes,10,rep,name=removed_actions,json=removedActions,proto3" json:"removed_actions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Reason          TerminationReason      `protobuf:"varint,11,opt,name=reason,proto3,enum=gostage.v3.process.TerminationReason" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResultSummary) Reset() {
	*x = ResultSummary{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultSummary) ProtoMessage() {}

func (x *ResultSummary) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultSummary.ProtoReflect.Descriptor instead.
func (*ResultSummary) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *ResultSummary) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResultSummary) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResultSummary) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ResultSummary) GetOutputJson() []byte {
	if x != nil {
		return x.OutputJson
	}
	return nil
}

func (x *ResultSummary) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ResultSummary) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ResultSummary) GetDisabledStages() map[string]bool {
	if x != nil {
		return x.DisabledStages
	}
	return nil
}

func (x *ResultSummary) GetDisabledActions() map[string]bool {
	if x != nil {
		return x.DisabledActions
	}
	return nil
}

func (x *ResultSummary) GetRemovedStages() map[string]string {
	if x != nil {
		return x.RemovedStages
	}
	return nil
}

func (x *ResultSummary) GetRemovedActions() map[string]string {
	if x != nil {
		return x.RemovedActions
	}
	return nil
}

func (x *ResultSummary) GetReason() TerminationReason {
	if x != nil {
		return x.Reason
	}
	return TerminationReason_TERMINATION_UNKNOWN
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x12gostage.v3.process\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x05\n" +
	"\x0fControlEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12>\n" +
	"\bregister\x18\x02 \x01(\v2 .gostage.v3.process.RegisterNodeH\x00R\bregister\x12D\n" +
	"\fregister_ack\x18\x03 \x01(\v2\x1f.gostage.v3.process.RegisterAckH\x00R\vregisterAck\x12A\n" +
	"\vlease_grant\x18\x04 \x01(\v2\x1e.gostage.v3.process.LeaseGrantH\x00R\n" +
	"leaseGrant\x12;\n" +
	"\tlease_ack\x18\x05 \x01(\v2\x1c.gostage.v3.process.LeaseAckH\x00R\bleaseAck\x12<\n" +
	"\x06cancel\x18\x06 \x01(\v2\".gostage.v3.process.CancelWorkflowH\x00R\x06cancel\x12=\n" +
	"\theartbeat\x18\a \x01(\v2\x1d.gostage.v3.process.HeartbeatH\x00R\theartbeat\x12:\n" +
	"\bshutdown\x18\b \x01(\v2\x1c.gostage.v3.process.ShutdownH\x00R\bshutdown\x12D\n" +
	"\ttelemetry\x18\t \x01(\v2$.gostage.v3.process.TelemetryForwardH\x00R\ttelemetry\x12G\n" +
	"\n" +
	"diagnostic\x18\n" +
	" \x01(\v2%.gostage.v3.process.DiagnosticForwardH\x00R\n" +
	"diagnostic\x12L\n" +
	"\rconfig_update\x18\v \x01(\v2%.gostage.v3.process.ChildConfigUpdateH\x00R\fconfigUpdateB\x06\n" +
	"\x04body\"\xde\x02\n" +
	"\fRegisterNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"child_type\x18\x02 \x01(\tR\tchildType\x123\n" +
	"\x05pools\x18\x03 \x03(\v2\x1d.gostage.v3.process.ChildPoolR\x05pools\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..gostage.v3.process.RegisterNode.MetadataEntryR\bmetadata\x129\n" +
	"\aruntime\x18\x05 \x01(\v2\x1f.gostage.v3.process.RuntimeInfoR\aruntime\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x06 \x01(\tR\tauthToken\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\vRegisterAck\x12H\n" +
	"\x12heartbeat_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\x12F\n" +
	"\x11heartbeat_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x10heartbeatTimeout\"\xcf\x01\n" +
	"\tChildPool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05slots\x18\x02 \x01(\rR\x05slots\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.gostage.v3.process.ChildPool.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\vRuntimeInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"go_version\x18\x02 \x01(\tR\tgoVersion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x16\n" +
	"\x06binary\x18\x05 \x01(\tR\x06binary\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x06 \x01(\tR\tgitCommit\"\x8e\x02\n" +
	"\n" +
	"LeaseGrant\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12!\n" +
	"\fworkflow_ref\x18\x04 \x01(\tR\vworkflowRef\x12'\n" +
	"\x0fdefinition_json\x18\x05 \x01(\fR\x0edefinitionJson\x12\x1d\n" +
	"\n" +
	"store_json\x18\x06 \x01(\fR\tstoreJson\x12#\n" +
	"\rmetadata_json\x18\a \x01(\fR\fmetadataJson\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\"\x83\x01\n" +
	"\bLeaseAck\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12;\n" +
	"\asummary\x18\x03 \x01(\v2!.gostage.v3.process.ResultSummaryR\asummary\"1\n" +
	"\x0eCancelWorkflow\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"a\n" +
	"\tHeartbeat\x12;\n" +
	"\vobserved_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\"\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"1\n" +
	"\x10TelemetryForward\x12\x1d\n" +
	"\n" +
	"event_json\x18\x01 \x01(\fR\teventJson\"\xc5\x01\n" +
	"\x11DiagnosticForward\x12;\n" +
	"\voccurred_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\fR\fmetadataJson\"8\n" +
	"\x11ChildConfigUpdate\x12#\n" +
	"\rmetadata_json\x18\x01 \x01(\fR\fmetadataJson\"\xbb\a\n" +
	"\rResultSummary\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x1f\n" +
	"\voutput_json\x18\x04 \x01(\fR\n" +
	"outputJson\x125\n" +
	"\bduration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12^\n" +
	"\x0fdisabled_stages\x18\a \x03(\v25.gostage.v3.process.ResultSummary.DisabledStagesEntryR\x0edisabledStages\x12a\n" +
	"\x10disabled_actions\x18\b \x03(\v26.gostage.v3.process.ResultSummary.DisabledActionsEntryR\x0fdisabledActions\x12[\n" +
	"\x0eremoved_stages\x18\t \x03(\v24.gostage.v3.process.ResultSummary.RemovedStagesEntryR\rremovedStages\x12^\n" +
	"\x0fremoved_actions\x18\n" +
	" \x03(\v25.gostage.v3.process.ResultSummary.RemovedActionsEntryR\x0eremovedActions\x12=\n" +
	"\x06reason\x18\v \x01(\x0e2%.gostage.v3.process.TerminationReasonR\x06reason\x1aA\n" +
	"\x13DisabledStagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1aB\n" +
	"\x14DisabledActionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a@\n" +
	"\x12RemovedStagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13RemovedActionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xb3\x01\n" +
	"\x11TerminationReason\x12\x17\n" +
	"\x13TERMINATION_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13TERMINATION_SUCCESS\x10\x01\x12\x17\n" +
	"\x13TERMINATION_FAILURE\x10\x02\x12\x1b\n" +
	"\x17TERMINATION_USER_CANCEL\x10\x03\x12\x1d\n" +
	"\x19TERMINATION_POLICY_CANCEL\x10\x04\x12\x17\n" +
	"\x13TERMINATION_TIMEOUT\x10\x052h\n" +
	"\rProcessBridge\x12W\n" +
	"\aControl\x12#.gostage.v3.process.ControlEnvelope\x1a#.gostage.v3.process.ControlEnvelope(\x010\x01B?Z=github.com/davidroman0O/gostage/v3/process/proto;processprotob\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_control_proto_goTypes = []any{
	(TerminationReason)(0),        // 0: gostage.v3.process.TerminationReason
	(*ControlEnvelope)(nil),       // 1: gostage.v3.process.ControlEnvelope
	(*RegisterNode)(nil),          // 2: gostage.v3.process.RegisterNode
	(*RegisterAck)(nil),           // 3: gostage.v3.process.RegisterAck
	(*ChildPool)(nil),             // 4: gostage.v3.process.ChildPool
	(*RuntimeInfo)(nil),           // 5: gostage.v3.process.RuntimeInfo
	(*LeaseGrant)(nil),            // 6: gostage.v3.process.LeaseGrant
	(*LeaseAck)(nil),              // 7: gostage.v3.process.LeaseAck
	(*CancelWorkflow)(nil),        // 8: gostage.v3.process.CancelWorkflow
	(*Heartbeat)(nil),             // 9: gostage.v3.process.Heartbeat
	(*Shutdown)(nil),              // 10: gostage.v3.process.Shutdown
	(*TelemetryForward)(nil),      // 11: gostage.v3.process.TelemetryForward
	(*DiagnosticForward)(nil),     // 12: gostage.v3.process.DiagnosticForward
	(*ChildConfigUpdate)(nil),     // 13: gostage.v3.process.ChildConfigUpdate
	(*ResultSummary)(nil),         // 14: gostage.v3.process.ResultSummary
	nil,                           // 15: gostage.v3.process.RegisterNode.MetadataEntry
	nil,                           // 16: gostage.v3.process.ChildPool.MetadataEntry
	nil,                           // 17: gostage.v3.process.ResultSummary.DisabledStagesEntry
	nil,                           // 18: gostage.v3.process.ResultSummary.DisabledActionsEntry
	nil,                           // 19: gostage.v3.process.ResultSummary.RemovedStagesEntry
	nil,                           // 20: gostage.v3.process.ResultSummary.RemovedActionsEntry
	(*durationpb.Duration)(nil),   // 21: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_control_proto_depIdxs = []int32{
	2,  // 0: gostage.v3.process.ControlEnvelope.register:type_name -> gostage.v3.process.RegisterNode
	3,  // 1: gostage.v3.process.ControlEnvelope.register_ack:type_name -> gostage.v3.process.RegisterAck
	6,  // 2: gostage.v3.process.ControlEnvelope.lease_grant:type_name -> gostage.v3.process.LeaseGrant
	7,  // 3: gostage.v3.process.ControlEnvelope.lease_ack:type_name -> gostage.v3.process.LeaseAck
	8,  // 4: gostage.v3.process.ControlEnvelope.cancel:type_name -> gostage.v3.process.CancelWorkflow
	9,  // 5: gostage.v3.process.ControlEnvelope.heartbeat:type_name -> gostage.v3.process.Heartbeat
	10, // 6: gostage.v3.process.ControlEnvelope.shutdown:type_name -> gostage.v3.process.Shutdown
	11, // 7: gostage.v3.process.ControlEnvelope.telemetry:type_name -> gostage.v3.process.TelemetryForward
	12, // 8: gostage.v3.process.ControlEnvelope.diagnostic:type_name -> gostage.v3.process.DiagnosticForward
	13, // 9: gostage.v3.process.ControlEnvelope.config_update:type_name -> gostage.v3.process.ChildConfigUpdate
	4,  // 10: gostage.v3.process.RegisterNode.pools:type_name -> gostage.v3.process.ChildPool
	15, // 11: gostage.v3.process.RegisterNode.metadata:type_name -> gostage.v3.process.RegisterNode.MetadataEntry
	5,  // 12: gostage.v3.process.RegisterNode.runtime:type_name -> gostage.v3.process.RuntimeInfo
	21, // 13: gostage.v3.process.RegisterAck.heartbeat_interval:type_name -> google.protobuf.Duration
	21, // 14: gostage.v3.process.RegisterAck.heartbeat_timeout:type_name -> google.protobuf.Duration
	16, // 15: gostage.v3.process.ChildPool.metadata:type_name -> gostage.v3.process.ChildPool.MetadataEntry
	14, // 16: gostage.v3.process.LeaseAck.summary:type_name -> gostage.v3.process.ResultSummary
	22, // 17: gostage.v3.process.Heartbeat.observed_at:type_name -> google.protobuf.Timestamp
	22, // 18: gostage.v3.process.DiagnosticForward.occurred_at:type_name -> google.protobuf.Timestamp
	21, // 19: gostage.v3.process.ResultSummary.duration:type_name -> google.protobuf.Duration
	22, // 20: gostage.v3.process.ResultSummary.completed_at:type_name -> google.protobuf.Timestamp
	17, // 21: gostage.v3.process.ResultSummary.disabled_stages:type_name -> gostage.v3.process.ResultSummary.DisabledStagesEntry
	18, // 22: gostage.v3.process.ResultSummary.disabled_actions:type_name -> gostage.v3.process.ResultSummary.DisabledActionsEntry
	19, // 23: gostage.v3.process.ResultSummary.removed_stages:type_name -> gostage.v3.process.ResultSummary.RemovedStagesEntry
	20, // 24: gostage.v3.process.ResultSummary.removed_actions:type_name -> gostage.v3.process.ResultSummary.RemovedActionsEntry
	0,  // 25: gostage.v3.process.ResultSummary.reason:type_name -> gostage.v3.process.TerminationReason
	1,  // 26: gostage.v3.process.ProcessBridge.Control:input_type -> gostage.v3.process.ControlEnvelope
	1,  // 27: gostage.v3.process.ProcessBridge.Control:output_type -> gostage.v3.process.ControlEnvelope
	27, // [27:28] is the sub-list for method output_type
	26, // [26:27] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlEnvelope_Register)(nil),
		(*ControlEnvelope_RegisterAck)(nil),
		(*ControlEnvelope_LeaseGrant)(nil),
		(*ControlEnvelope_LeaseAck)(nil),
		(*ControlEnvelope_Cancel)(nil),
		(*ControlEnvelope_Heartbeat)(nil),
		(*ControlEnvelope_Shutdown)(nil),
		(*ControlEnvelope_Telemetry)(nil),
		(*ControlEnvelope_Diagnostic)(nil),
		(*ControlEnvelope_ConfigUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
