// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/workflow_ipc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowIPC_RequestWorkflowDefinition_FullMethodName = "/gostage.WorkflowIPC/RequestWorkflowDefinition"
	WorkflowIPC_SendMessage_FullMethodName               = "/gostage.WorkflowIPC/SendMessage"
)

// WorkflowIPCClient is the client API for WorkflowIPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkflowIPC service defines the communication between parent and child processes.
// Pull model: child connects to parent's gRPC server, requests work, returns results.
type WorkflowIPCClient interface {
	// Child requests workflow definition from parent
	RequestWorkflowDefinition(ctx context.Context, in *ReadySignal, opts ...grpc.CallOption) (*WorkflowDefinition, error)
	// Send a single message from child to parent (IPC, final store, results)
	SendMessage(ctx context.Context, in *IPCMessage, opts ...grpc.CallOption) (*MessageAck, error)
}

type workflowIPCClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowIPCClient(cc grpc.ClientConnInterface) WorkflowIPCClient {
	return &workflowIPCClient{cc}
}

func (c *workflowIPCClient) RequestWorkflowDefinition(ctx context.Context, in *ReadySignal, opts ...grpc.CallOption) (*WorkflowDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowDefinition)
	err := c.cc.Invoke(ctx, WorkflowIPC_RequestWorkflowDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowIPCClient) SendMessage(ctx context.Context, in *IPCMessage, opts ...grpc.CallOption) (*MessageAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageAck)
	err := c.cc.Invoke(ctx, WorkflowIPC_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowIPCServer is the server API for WorkflowIPC service.
// All implementations must embed UnimplementedWorkflowIPCServer
// for forward compatibility.
//
// WorkflowIPC service defines the communication between parent and child processes.
// Pull model: child connects to parent's gRPC server, requests work, returns results.
type WorkflowIPCServer interface {
	// Child requests workflow definition from parent
	RequestWorkflowDefinition(context.Context, *ReadySignal) (*WorkflowDefinition, error)
	// Send a single message from child to parent (IPC, final store, results)
	SendMessage(context.Context, *IPCMessage) (*MessageAck, error)
	mustEmbedUnimplementedWorkflowIPCServer()
}

// UnimplementedWorkflowIPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowIPCServer struct{}

func (UnimplementedWorkflowIPCServer) RequestWorkflowDefinition(context.Context, *ReadySignal) (*WorkflowDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestWorkflowDefinition not implemented")
}
func (UnimplementedWorkflowIPCServer) SendMessage(context.Context, *IPCMessage) (*MessageAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedWorkflowIPCServer) mustEmbedUnimplementedWorkflowIPCServer() {}
func (UnimplementedWorkflowIPCServer) testEmbeddedByValue()                     {}

// UnsafeWorkflowIPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowIPCServer will
// result in compilation errors.
type UnsafeWorkflowIPCServer interface {
	mustEmbedUnimplementedWorkflowIPCServer()
}

func RegisterWorkflowIPCServer(s grpc.ServiceRegistrar, srv WorkflowIPCServer) {
	// If the following call panics, it indicates UnimplementedWorkflowIPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowIPC_ServiceDesc, srv)
}

func _WorkflowIPC_RequestWorkflowDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadySignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowIPCServer).RequestWorkflowDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowIPC_RequestWorkflowDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowIPCServer).RequestWorkflowDefinition(ctx, req.(*ReadySignal))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowIPC_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPCMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowIPCServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowIPC_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowIPCServer).SendMessage(ctx, req.(*IPCMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowIPC_ServiceDesc is the grpc.ServiceDesc for WorkflowIPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowIPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gostage.WorkflowIPC",
	HandlerType: (*WorkflowIPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestWorkflowDefinition",
			Handler:    _WorkflowIPC_RequestWorkflowDefinition_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _WorkflowIPC_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/workflow_ipc.proto",
}
