// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: control.proto

package processproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessBridge_Control_FullMethodName = "/gostage.v3.process.ProcessBridge/Control"
)

// ProcessBridgeClient is the client API for ProcessBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProcessBridge exposes the bidirectional control stream between parent and child.
type ProcessBridgeClient interface {
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlEnvelope, ControlEnvelope], error)
}

type processBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessBridgeClient(cc grpc.ClientConnInterface) ProcessBridgeClient {
	return &processBridgeClient{cc}
}

func (c *processBridgeClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlEnvelope, ControlEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessBridge_ServiceDesc.Streams[0], ProcessBridge_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlEnvelope, ControlEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessBridge_ControlClient = grpc.BidiStreamingClient[ControlEnvelope, ControlEnvelope]

// ProcessBridgeServer is the server API for ProcessBridge service.
// All implementations must embed UnimplementedProcessBridgeServer
// for forward compatibility.
//
// ProcessBridge exposes the bidirectional control stream between parent and child.
type ProcessBridgeServer interface {
	Control(grpc.BidiStreamingServer[ControlEnvelope, ControlEnvelope]) error
	mustEmbedUnimplementedProcessBridgeServer()
}

// UnimplementedProcessBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessBridgeServer struct{}

func (UnimplementedProcessBridgeServer) Control(grpc.BidiStreamingServer[ControlEnvelope, ControlEnvelope]) error {
	return status.Errorf(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedProcessBridgeServer) mustEmbedUnimplementedProcessBridgeServer() {}
func (UnimplementedProcessBridgeServer) testEmbeddedByValue()                       {}

// UnsafeProcessBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessBridgeServer will
// result in compilation errors.
type UnsafeProcessBridgeServer interface {
	mustEmbedUnimplementedProcessBridgeServer()
}

func RegisterProcessBridgeServer(s grpc.ServiceRegistrar, srv ProcessBridgeServer) {
	// If the following call pancis, it indicates UnimplementedProcessBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessBridge_ServiceDesc, srv)
}

func _ProcessBridge_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProcessBridgeServer).Control(&grpc.GenericServerStream[ControlEnvelope, ControlEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessBridge_ControlServer = grpc.BidiStreamingServer[ControlEnvelope, ControlEnvelope]

// ProcessBridge_ServiceDesc is the grpc.ServiceDesc for ProcessBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gostage.v3.process.ProcessBridge",
	HandlerType: (*ProcessBridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _ProcessBridge_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "control.proto",
}
